cpims/urls.py
"""
cpims URL Configuration.

Other urls are import
Put here only urls not specific to app
"""
from django.conf.urls import include, url
from django.contrib import admin
from cpovc_auth import urls as auth_urls
from cpovc_registry import urls as registry_urls
from cpovc_forms import urls as forms_urls
from cpovc_reports import urls as reports_urls
from cpovc_gis import urls as gis_urls
from cpovc_api import urls as api_urls
from cpovc_ovc import urls as ovc_urls
from cpovc_settings import urls as settings_urls
from django.contrib.auth.views import (
    password_reset_done, password_change, password_change_done)
from cpovc_auth.views import password_reset
from django.views.generic import TemplateView

from cpovc_access.forms import StrictPasswordChangeForm


urlpatterns = [
    url(r'^admin/', include(admin.site.urls), name='admin'),
    # url(r'^$', 'cpovc_auth.views.log_in', name='home'),
    url(r'^$', 'cpims.views.public_dash', name='public_dash'),
    url(r'^hiv_stats_pub_data/(?P<org_level>\w+)/(?P<org_level_sub_level>.*)/', 'cpims.views.get_pub_data', name='get_pub_data'),
    url(r'^get_hiv_suppression_data/(?P<org_level>\w+)/(?P<org_level_sub_level>.*)/', 'cpims.views.get_hiv_suppression_data', name='get_hiv_suppression_data'),
    url(r'^home/$', 'cpims.views.home', name='home'),
    url(r'^accounts/request/$', 'cpims.views.access', name='access'),
    url(r'^accounts/terms/(?P<id>\d+)/$', 'cpovc_access.views.terms',
        name='terms'),
    url(r'^login/$', 'cpovc_auth.views.log_in', name='login'),
    url(r'^logout/$', 'cpovc_auth.views.log_out', name='logout'),
    url(r'^register/$', 'cpovc_auth.views.register', name='register'),
    url(r'^auth/', include(auth_urls)),
    url(r'^registry/', include(registry_urls)),
    url(r'^forms/', include(forms_urls)),
    url(r'^reports/', include(reports_urls)),
    url(r'^gis/', include(gis_urls)),
    url(r'^api/', include(api_urls)),
    url(r'^ovcare/', include(ovc_urls)),
    url(r'^settings/', include(settings_urls)),
    url(r'^accounts/login/$', 'cpovc_auth.views.log_in', name='login'),
    url(r'^accounts/password/reset/$', password_reset,
        {'template_name': 'registration/password_reset.html'},
        name='password_reset'),
    url(r'^accounts/password/reset/done/$', password_reset_done,
        {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^accounts/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'cpovc_auth.views.reset_confirm', name='password_reset_confirm'),
    url(r'^reset/$', 'cpovc_auth.views.reset', name='reset'),
    url(r'^accounts/password/change/$', password_change,
        {'post_change_redirect': '/accounts/password/change/done/',
         'template_name': 'registration/password_change.html',
         'password_change_form': StrictPasswordChangeForm},
        name='password_change'),
    url(r'^accounts/password/change/done/$', password_change_done,
        {'template_name': 'registration/password_change_done.html'}),
    url(r'^F57665A859FE7CFCDB6C8935196374AD\.txt$',
        TemplateView.as_view(template_name='comodo.txt',
                             content_type='text/plain')),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
                                               content_type='text/plain'))]

handler400 = 'cpims.views.handler_400'
handler404 = 'cpims.views.handler_404'
handler500 = 'cpims.views.handler_500'

admin.site.site_header = 'CPIMS Administration'
admin.site.site_title = 'CPIMS administration'
admin.site.index_title = 'CPIMS admin'

cpovc_auth/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin, Group, Permission)
from datetime import datetime
from django.db.models.signals import pre_save
from django.dispatch import receiver


class CPOVCUserManager(BaseUserManager):

    def create_user(self, username, reg_person, password=None):

        from cpovc_registry.models import RegPerson
        if not username:
            raise ValueError('The given username must be set')

        now = datetime.now()
        user = self.model(username=username,
                          reg_person=RegPerson.objects.get(pk=int(reg_person)),
                          password=password,
                          is_staff=False,
                          is_active=True,
                          is_superuser=False,
                          role='Public',
                          timestamp_created=now,
                          timestamp_updated=now,
                          )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, reg_person, password=None):
        user = self.create_user(username=username,
                                reg_person=reg_person,
                                password=password
                                )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class AppUser(AbstractBaseUser, PermissionsMixin):
    reg_person = models.OneToOneField('cpovc_registry.RegPerson', null=False)
    role = models.CharField(max_length=20, unique=False, default='Public')
    username = models.CharField(max_length=20, unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    timestamp_created = models.DateTimeField(auto_now_add=True)
    timestamp_updated = models.DateTimeField(auto_now=True)
    password_changed_timestamp = models.DateTimeField(null=True)

    # For admin so remove if you don't want to use admin
    first_name = False
    last_name = False
    date_joined = False

    objects = CPOVCUserManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['reg_person']

    def _get_email(self):
        return self.reg_person.email

    email = property(_get_email)

    def _get_sex(self):
        sex_id = self.reg_person.sex_id
        sex = 'Male' if sex_id == 'SMAL' else 'Female'
        return sex

    sex = property(_get_sex)

    def _get_first_name(self):
        return self.reg_person.first_name

    first_name = property(_get_first_name)

    def _get_surname(self):
        return self.reg_person.surname

    surname = property(_get_surname)

    def _get_last_name(self):
        return self.reg_person.other_names

    last_name = property(_get_last_name)

    def get_full_name(self):
        """
        TO DO - Get this from persons table but for now just use
        Workforce ID
        """
        return self.username

    def get_short_name(self):
        """
        Return Workforce ID if exists or not
        """
        return self.username

    def get_username(self):
        """
        Return National ID if exists else Workforce ID
        """
        if self.username:
            return self.username
        else:
            return None

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        db_table = 'auth_user'


class CPOVCPermission(Permission):
    permission_description = models.CharField(max_length=255)
    permission_set = models.CharField(max_length=100)
    permission_type = models.CharField(max_length=50, blank=True)
    restricted_to_self = models.BooleanField(blank=True, default=False)
    restricted_to_org_unit = models.BooleanField(blank=True, default=False)
    restricted_to_geo = models.BooleanField(blank=True, default=False)
    timestamp_modified = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = 'auth_permission_detail'


class CPOVCRole(Group):
    group_id = models.CharField(max_length=5)
    group_name = models.CharField(max_length=100)
    group_description = models.CharField(max_length=255)
    restricted_to_org_unit = models.BooleanField(blank=True, default=False)
    restricted_to_geo = models.BooleanField(blank=True, default=False)
    automatic = models.BooleanField(default=False)
    timestamp_modified = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = 'auth_group_detail'


class CPOVCUserRoleGeoOrg(models.Model):
    # Put here to avoid cyclic imports because of User model
    # from cpovc_registry.models import RegPersonsGeo, RegOrgUnit
    user = models.ForeignKey(AppUser)
    group = models.ForeignKey(CPOVCRole)
    org_unit = models.ForeignKey('cpovc_registry.RegOrgUnit', null=True)
    area = models.ForeignKey('cpovc_main.SetupGeography', null=True)
    timestamp_modified = models.DateTimeField(default=timezone.now)
    is_void = models.BooleanField(default=False)

    class Meta:
        db_table = 'auth_user_groups_geo_org'


@receiver(pre_save, sender=AppUser)
def update_change(sender, instance, **kwargs):
    """Method to Update pwd change."""
    try:
        obj = sender.objects.get(pk=instance.pk)
    except sender.DoesNotExist:
        print "User does not exist"
        pass
    else:
        if obj.password != instance.password:
            print "Password changed so update date."
        else:
            print "Password NOT changed so NO update."

templates/reports/cluster.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block page_title %} Reports clusters {% endblock %}

{% load crispy_forms_tags %}

{% block style_code %}

{% endblock %}

{% block primary %}
<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
	<li><a href="#">Home</a></li>
	<li class="active">Clusters</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header"><i class="fa fa-area-chart"></i> Reports <small>Clusters</small></h1>
<!-- end page-header -->
<div id="message"></div>
<div id="messages" class="alert alert-danger fade in" style="display: none;" tabindex="1">
    <span class="close" data-dismiss="alert">×</span>
    <i class="fa fa-check fa-2x pull-left"></i>
    <span class="invalid-form-message" id="invalid-form-message"></span>
</div>
{% if messages %}
    {% for message in messages %}
    {% if 'error' in message.tags %}
        <div id="messages" class="alert alert-danger fade in">
        <span class="close" data-dismiss="alert">×</span>
        <i class="fa fa-info fa-2x pull-left"></i>
    {% else %}
        <div id="messages" class="alert alert-success fade in">
        <span class="close" data-dismiss="alert">×</span>
        <i class="fa fa-check fa-2x pull-left"></i>
    {% endif %}    
        <p>{{ message }}</p>
    </div>
   {% endfor %}
{% endif %}
<!-- begin row -->
<div class="row">
  <!-- begin col-12 -->
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>                      
                <h4 class="panel-title">Cluster management &nbsp;</h4>
            </div>
            <!-- start panel body -->
            <div class="panel-body">
                <form class="form-horizontal form-bordered" action="." method="POST" data-parsley-validate="true" name="form-wizard" id="clusters">
                    {% csrf_token %}
                    <!-- begin col-4 -->
                    <div class="row">
                        <div class="col-md-5">
                            <div class="form-group block1">
                                <label for="person_type">Cluster Name <span class="asteriskField">*</span></label><br/><br/>
                                {{ form.cluster }}
                            </div>
                        </div>
                        <!-- end col-4 -->
                        <div class="col-md-5">
                            <div id="is_caregiver_div" class="form-group block1">
                                <label for="is_caregiver">Organisation Units / CBOs <span class="asteriskField"></span></label>
                                {{ form.cbo }} 
                            </div>
                        </div>
                        <!-- end col-4 -->
                        <!-- end col-2 -->
                        <div class="col-md-2">
                            <div id="is_caregiver_div" class="form-group block1">
                                <label for="is_caregiver"><br/></label><br/><br/>
                                <button type="submit" class="btn btn-sm btn-primary m-r-10"><i class="fa fa-check-square-o"></i> Create </button>
                            </div>
                        </div>
                        <!-- end col-2 -->
                    </div>
                </form>
                <hr>
                <b><p>My / Organisation Clusters</p></b>
                <div class="table-responsive">
                <table id="data-table" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th width="5%">ID</th>
                            <th>Name</th>
                            <th>CBOs</th>
                            <th>Created By</th>
                            <th>Date Created</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for cluster in clusters %}
                        <tr id="cluster_tr_{{ cluster.id }}">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ cluster.cluster_name }}</td>
                            <td><ol>
                            {% for cbo in cluster.cbos %}
                            <li>{{ cbo }}</li>
                            {% endfor %}
                            </ol>
                            </td>
                            <td>{{ cluster.created_by.first_name }} {{ cluster.created_by.surname }}</td>
                            <td>{{ cluster.created_at }}</td>
                            <td>
                            {% if request.user.id == cluster.created_by.id %}
                                <button type="button" id="{{ cluster.id }}" class="btn btn-sm btn-danger m-r-10 remove_cluster"><i class="fa fa-trash"></i> </button>
                            {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    </table>
                </div>
            </div>
            <!-- end panel body -->
        </div>
        <!-- end panel -->  
    </div>
    <!-- end col-12 -->
</div>
<!-- end row -->
{% endblock %}

{% block lazy_javascript_code %}
<script type="text/javascript" src="{% static 'js/bootstrap-multiselect.js' %}"></script>
<script>
jQuery(document).ready(function() {
    $('#cbo').multiselect({
        selectAllValue: 'multiselect-all',
        includeSelectAllOption: true,
        enableCaseInsensitiveFiltering: true,
        numberDisplayed: 1,
        maxHeight: 300,
        buttonWidth: '100%',
        disableIfEmpty: true,
        enableClickableOptGroups: true,
        buttonClass: 'btn btn-white'
    });
    $("#data-table").delegate(".remove_cluster", "click", function() {
        var id = $(this).attr('id');
        //var cluster = $(this).attr('cluster_id');
       $.ajax({
               type: "POST",
               url: "{% url 'cluster' %}",
               data: $("#clusters").serialize() + "&id="+id,
               success: function(data)
               {
                   var status_id = data.status;
                   if (status_id == 0){
                       $("#cluster_tr_"+id+"").remove();
                       $("#message").addClass( "alert alert-success fade in" );
                       $('#message').html("Cluster removed successfully.");
                   }else{
                       $("#message").addClass( "alert alert-danger fade in" );
                       $('#message').html("Error removing cluster");
                   }
               },
                error: function(){
                    $("#message").addClass( "alert alert-danger fade in" );
                    $('#message').html("Error removing cluster");
                }
        });
    });
});
</script>
{% endblock %}

templates/reports/reports_documents.html
{% extends 'base.html' %}
{% block page_title %} {{block.super}}Reports{% endblock page_title%}

{% load staticfiles %}

{% block primary%}
<h1 class="page-header">Reports <small>Document templates</small></h1>

{% if messages %}
<div id="messages" class="alert alert-danger fade in">
    <span class="close" data-dismiss="alert">×</span>
    <i class="fa fa-check fa-2x pull-left"></i>
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.error %} class="{{ message.danger }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

<!-- begin row -->
<div class="row">
    <!-- begin col-12 -->
    <div class="col-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="#" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                </div>                        
                <h4 class="panel-title">Report / document details</h4>
            </div>
            <div class="panel-body">
				    <form id="manage-docs" class="form-horizontal form-bordered" action="{% url 'reports' %}" method="POST" data-parsley-validate="true">
               {% csrf_token %}
                <div class="form-group">
                    <label class="control-label col-md-4 col-sm-4">Organisation Unit :</label>
                    <div class="col-md-6 col-sm-6">
                        {{ form.org_unit }}
                    </div>
                    <a href="#" data-toggle="tooltip" title="Select at least one sub-county."><i class="fa fa-info-circle fa-lg"></i></a>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-4 col-sm-4">Report / document type :</label>
                    <div class="col-md-6 col-sm-6">
                      {{ form.document_type }}
                    </div>
                    <a href="#" data-toggle="tooltip" title="Select report type."><i class="fa fa-info-circle fa-lg"></i></a>
					      </div>
      					<div class="form-group">
                      <label class="control-label col-md-4 col-sm-4">Child :</label>
                      <div class="col-md-6 col-sm-6">
                        {{ form.child }} {{ form.cpims_child }}
                        <div id="case_details"></div>
                      </div>
                      <a href="#" data-toggle="tooltip" title="Start typing name of child."><i class="fa fa-info-circle fa-lg"></i></a>
      					</div>
      					<div class="form-group" id="case_more">
                      <label class="control-label col-md-4 col-sm-4">Case details : </label>
                      <div class="col-md-6 col-sm-6" id="case_data">
                         <div id="case_id_error"></div>
                      </div>                                            
      					</div>
                <div class="form-group" id="case_proceed">
                      <label class="control-label col-md-4 col-sm-4"></label>
                      <div class="col-md-6 col-sm-6">
                          <button type="submit" class="btn btn-sm btn-primary m-r-5"><i class="fa fa-check-square-o"></i> Generate</button>
                      </div>
                </div>
				  </form>
			</div>
      <!-- end panel body -->
    </div>
    <!-- end panel -->
      <div id="report_results">
            {% if results|length %}
                <div class="table-responsive">
                <button type="button" class="btn btn-info m-r-5 m-b-5"> 
                <i class="fa fa-folder-open-o"></i> Preview</button>
                <a href="{% url 'download_reports' file_name=file_name %}.xls">
                  <button type="button" class="btn btn-success m-r-5 m-b-5">
                  <i class="fa fa-file-excel-o"></i> Excel</button>
                </a>
                <a href="{% url 'download_reports' file_name=file_name %}.pdf">
                  <button type="button" class="btn btn-danger m-r-5 m-b-5"> 
                  <i class="fa fa-file-pdf-o"></i> PDF</button>
                </a>
                <a href="{% url 'download_reports' file_name=file_name %}.csv">
                  <button type="button" class="btn btn-warning m-r-5 m-b-5">
                  <i class="fa fa-file-text-o"></i> CSV</button>
                </a>
                  </div>
              {% endif %}
        </div>
    </div>
    <!-- end col-12 -->       
</div>
<!-- end row -->

{% endblock primary%}

{% block lazy_javascript_code %}
<script>
jQuery(document).ready(function() {
    $('#id_org_unit').attr('data-parsley-required', 'true');
    $('#manage-docs').on('submit', function(event){
	    event.preventDefault();
	    var doc_name = $('#id_document_type option:selected').text();
      $('#report_results').html("Processing Document...");
	    $.ajax({
	        url : "{% url 'reports' %}",
	        type : "POST",
	        data: $("#manage-docs").serialize()+ "&doc_name="+ doc_name,
	        // handle a successful response
	        success : function(jsondata) {
	        	  var file_name = jsondata.file_name;
	        	  var url = '<a href="{% url "download_reports" file_name="0000" %}.pdf">';
	        	  var data = url.replace('0000', file_name);
				      data += '<button type="button" class="btn btn-danger m-r-5 m-b-5">';
				      data += '<i class="fa fa-file-pdf-o"></i> PDF</button></a>';
	            $('#report_results').html(data);
	        },
	        // handle a non-successful response
	        error : function(xhr, errmsg, err) {
	            $('#report_results').html("Oops! We have encountered an error: " + errmsg);
	            console.log(xhr.status + ": " + xhr.responseText);
	        }
	    });

	});
	$('#child_id').val('');
	$('#cpims_child_id').val('');
	$('#case_more').hide();
	$('#case_proceed').hide();
	// To get Children
    $( "#child_id" ).autocomplete({
        source: function( request, response ) {
        $.ajax({
          url: "{% url 'registry' %}",
          dataType: "json",
          data: {q: request.term, id: 1},
          success: function( data ) {
            response( data );
          }
        });
      },
      minLength: 4,
      appendTo: "#case_details",
      select: function( event, ui ) {
      	$('#case_more').show();
        var cases = ui.item.cases;
        var dt = "";
        var has_case;
        if(cases){
          has_case = 1;
          $.each(cases, function(i, item) {
            dt += '<input type="radio" name="case_id" value="'+item.id+'" data-parsley-required="true">';
            dt += item.serial+' | '+item.case_date+'<br>';
          });
        }else{
          has_case = 0;
          dt += "No active Case Record or Have no access";
        }       
  	    $('#case_data').html(dt);
        $('#cpims_child_id').val(ui.item.id);
        if (has_case == 1){          
           $('#case_proceed').show();
           $('#report_results').show();
        }else{
           $('#case_proceed').hide();
           $('#report_results').hide();
        }
      },
      open: function() {
        $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
      },
      close: function() {
        $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
      }
    });
});
</script>
{% endblock lazy_javascript_code %}

templates/reports/reports_manage.html
{% extends 'base.html' %}
{% block page_title %} {{block.super}} Manage Reports{% endblock page_title %}

{% load staticfiles %}
{% load app_filters %}

{% block style_code %}
<link href="{% static 'plugins/datatables/css/data-table.css' %}" rel="stylesheet" />
{% endblock style_code %}

{% block primary%}
<h1 class="page-header">Manage Reports</h1><small></small>

{% if messages %}
<div id="messages" class="alert alert-danger fade in">
    <span class="close" data-dismiss="alert">×</span>
    <i class="fa fa-check fa-2x pull-left"></i>
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.error %} class="{{ message.danger }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

<!-- begin row -->
<div class="row">
    <!-- begin col-2 -->
    <div class="col-md-2">
        <h5>
            Key features include:
        </h5>
        <ul class="p-l-25 m-b-15">
            <li>Download your earlier generated reports and templates</li>
            <li>View reports and templates generated by other staff in your Org unit</li>
            <li>Ability to view existing reports and templates</li>
            <li>Delete your earlier generated reports and templates.</li>
        </ul>
        <p class="m-b-20">
            <a href="{% url 'manage_dashboard' %}" class="btn btn-inverse btn-sm">View my Dashboard</a>
        </p>
        <p class="m-b-20">
            <a href="#" class="btn btn-danger btn-sm">Disk Usage {{ fusage }}</a>
        </p>
    </div>
    <!-- end col-2 -->
    <!-- begin col-10 -->
    <div class="col-md-10">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
                <h4 class="panel-title">Created Reports and Templates</h4>
            </div>
            <div class="alert alert-warning fade in">
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div id="mng_messages">
                These are reports and templates generated by users and temporarily saved on the server for easier download. <br/>You can manage your own or your Organisation Unit reports from here:
                </div>
            </div>
            <div class="panel-body">
                <form id="manage-rpts">
                    {% csrf_token %}
                </form>
                <div class="table-responsive">
                    <table id="data-table" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Report Type</th>
                                <th>Created by</th>
                                <th>Region</th>
                                <th>Period</th>
                                <th>Create datetime</th>
                                <th>Size(KB)</th>
                                <th width="15%">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for val in data %}
                                <tr class="odd gradeX" id="report_{{ val.rid }}">
                                    <td>{{ val.rcount }}</td>
                                    <td>{{ val.rtype }} ({{ val.ftype }})</td>
                                    <td>{{ val.rby|gen_value:vals }}</td>
                                    <td>{{ val.rarea }}</td>
                                    <td>{{ val.rperiod }}</td>
                                    <td>{{ val.rcreate }}</td>
                                    <td>{{ val.fsize }}</td>
                                    <td>
                                    <a href='{% url "download_reports" file_name=val.rname %}'>
                                    <button type="button" class="btn btn-success"><i class="fa fa-download"></i></button></a>
                                    <button id = "{{ val.rid }}" rel="{{ val.rname }}" type="button" class="btn btn-danger remove_file"><i class="fa fa-trash-o"></i></button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- end panel -->
    </div>
    <!-- end col-10 -->
</div>
<!-- end row -->

{% endblock primary%}

{% block lazy_javascript_code %}
<script src="{% static 'plugins/datatables/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables/js/dataTables.colVis.js' %}"></script>

<script type="text/javascript">
var handleDataTableColVis = function() {
    "use strict";
    
    if ($('#data-table').length !== 0) {
        $('#data-table').DataTable({
            dom: 'C<"clear">lfrtip'
        });
    }
};

var TableManageColVis = function () {
    "use strict";
    return {
        //main function
        init: function () {
            handleDataTableColVis();
        }
    };
}();
$(document).ready(function() {
    TableManageColVis.init();

    $("#data-table").delegate(".remove_file", "click", function() {
        var id = $(this).attr('id');
        var fid = $(this).attr('rel');
       // Remove this file from the computer
       $.ajax({
           type: "POST",
           url: "{% url 'manage_reports' %}",
           data: $("#manage-rpts").serialize()+ "&report_id="+ fid,
           success: function(response)
           {
               var msg = response.msg;
               var status_id = response.status;
               if (status_id == 0){
                   $("#report_"+ id).remove();
               }
               $('#mng_messages').html(msg);
           },
            error: function(){
                $('#mng_messages').html("Error removing report")
            }
         });

    });
});
</script>
{% endblock lazy_javascript_code %}